name: ${project.name}
main: ${bukkitMainClass}
version: ${project.version}
authors: [JerryWood, TekkitCommando, Phillmac, Peda1996]
description: ${project.description}
website:  http://woominecraft.com

commands:
  woo:
    description: Check
    usage: |
        /<command> check - check for donations.
permissions:
  woo.admin:
    default: op
    description: Allows the player (or console) to use the woo commands.